name: Run Java Code

on:
  workflow_dispatch:       # ✅ Enables manual trigger from the GitHub Actions UI
  push:                    # ✅ Still triggers on push as usual
    branches:
      - main               # Adjust if you're using a different branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile Java code
        run: javac src/Main.java

      - name: Run Java program
        run: java -cp src Main
